-- ClarityBoard Database Initialization (PostgreSQL 18)
-- Run manually on local PostgreSQL instance:
--   psql -U app -d clarityboard -f infrastructure/postgres/init.sql
-- Creates schemas for multi-domain separation

CREATE SCHEMA IF NOT EXISTS accounting;
CREATE SCHEMA IF NOT EXISTS kpi;
CREATE SCHEMA IF NOT EXISTS entity;
CREATE SCHEMA IF NOT EXISTS cashflow;
CREATE SCHEMA IF NOT EXISTS scenario;
CREATE SCHEMA IF NOT EXISTS document;
CREATE SCHEMA IF NOT EXISTS budget;
CREATE SCHEMA IF NOT EXISTS asset;
CREATE SCHEMA IF NOT EXISTS integration;
CREATE SCHEMA IF NOT EXISTS ai;

-- Grant usage to application user
GRANT USAGE ON SCHEMA accounting TO app;
GRANT USAGE ON SCHEMA kpi TO app;
GRANT USAGE ON SCHEMA entity TO app;
GRANT USAGE ON SCHEMA cashflow TO app;
GRANT USAGE ON SCHEMA scenario TO app;
GRANT USAGE ON SCHEMA document TO app;
GRANT USAGE ON SCHEMA budget TO app;
GRANT USAGE ON SCHEMA asset TO app;
GRANT USAGE ON SCHEMA integration TO app;
GRANT USAGE ON SCHEMA ai TO app;

-- Grant table privileges
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO app;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA accounting TO app;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA kpi TO app;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA entity TO app;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA cashflow TO app;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA scenario TO app;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA document TO app;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA budget TO app;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA asset TO app;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA integration TO app;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA ai TO app;

-- Grant sequence privileges
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA accounting TO app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA kpi TO app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA entity TO app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA cashflow TO app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA scenario TO app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA document TO app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA budget TO app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA asset TO app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA integration TO app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA ai TO app;

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
