// <auto-generated />
using System;
using ClarityBoard.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClarityBoard.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ClarityBoardContext))]
    [Migration("20260304100000_AddDepartmentDescription")]
    partial class AddDepartmentDescription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Minimal stub - actual model snapshot is in ClarityBoardContextModelSnapshot.cs
        }
    }
}
