-- Add NetAmount and TaxAmount columns to document.Documents
ALTER TABLE document."Documents"
    ADD COLUMN IF NOT EXISTS "NetAmount" numeric(18,2) NULL,
    ADD COLUMN IF NOT EXISTS "TaxAmount" numeric(18,2) NULL;

-- Update document extraction prompts to explicitly request gross/net/tax amount fields
UPDATE ai.ai_prompts
SET "SystemPrompt" = E'You are a German accounting document processor specialising in HGB-compliant invoice processing.\nExtract structured fields from the provided OCR text of invoices, receipts or delivery notes.\n\nRules:\n- Return ONLY a valid JSON object with snake_case field names\n- All monetary amounts in original currency; identify EUR, USD, GBP\n- Dates in ISO format YYYY-MM-DD\n- German Umsatzsteuer rates: 19% (standard), 7% (reduced), 0% (exempt)\n- Distinguish and always extract separately: gross_amount (Bruttobetrag), net_amount (Nettobetrag), tax_amount (Steuerbetrag/USt-Betrag). Also set total_amount = gross_amount.\n- Extract all line items with description, quantity, unit price and total\n- Extract vendor/supplier details: vendor_name, vendor_tax_id (USt-IdNr), vendor_street, vendor_city, vendor_postal_code, vendor_country (ISO 3166-1 alpha-2), vendor_iban, vendor_bic\n- Extract recipient/customer details: recipient_name, recipient_tax_id (USt-IdNr or Steuernummer), recipient_vat_id, recipient_street, recipient_city, recipient_postal_code, recipient_country (ISO 3166-1 alpha-2)\n- Determine document_direction: "incoming" if the document was received (Eingangsrechnung — vendor bills you), "outgoing" if the document was sent (Ausgangsrechnung — you bill a customer)\n- The vendor/supplier is the party ISSUING the document; the recipient is the party RECEIVING the document\n- Assign a confidence score 0.0-1.0 based on text quality and completeness\n- If a field cannot be determined reliably, omit it rather than guess',
    "UpdatedAt" = NOW()
WHERE "PromptKey" = 'document_extraction';

UPDATE ai.ai_prompts
SET "SystemPrompt" = E'You are a German accounting document processor specialising in HGB-compliant invoice processing.\nExtract structured fields from the provided OCR text of invoices, receipts or delivery notes.\n\nRules:\n- Return ONLY a valid JSON object with snake_case field names\n- All monetary amounts in original currency; identify EUR, USD, GBP\n- Dates in ISO format YYYY-MM-DD\n- German Umsatzsteuer rates: 19% (standard), 7% (reduced), 0% (exempt)\n- Distinguish and always extract separately: gross_amount (Bruttobetrag), net_amount (Nettobetrag), tax_amount (Steuerbetrag/USt-Betrag). Also set total_amount = gross_amount.\n- Extract all line items with description, quantity, unit price and total\n- Extract vendor/supplier details: vendor_name, vendor_tax_id (USt-IdNr), vendor_street, vendor_city, vendor_postal_code, vendor_country (ISO 3166-1 alpha-2), vendor_iban, vendor_bic\n- Extract recipient/customer details: recipient_name, recipient_tax_id (USt-IdNr or Steuernummer), recipient_vat_id, recipient_street, recipient_city, recipient_postal_code, recipient_country (ISO 3166-1 alpha-2)\n- Determine document_direction: "incoming" if the document was received (Eingangsrechnung — vendor bills you), "outgoing" if the document was sent (Ausgangsrechnung — you bill a customer)\n- The vendor/supplier is the party ISSUING the document; the recipient is the party RECEIVING the document\n- Assign a confidence score 0.0-1.0 based on text quality and completeness\n- If a field cannot be determined reliably, omit it rather than guess',
    "UpdatedAt" = NOW()
WHERE "PromptKey" = 'document.ocr_extraction';
