namespace ClarityBoard.Infrastructure.Persistence.Seed;

public static class Skr03Accounts
{
    public record AccountSeed(string Number, string Name, string AccountType, short AccountClass, string? VatDefault = null);

    public static readonly AccountSeed[] All = [
        // Class 0: Anlage- und Kapitalkonten (Asset & Capital)
        new("0010", "Grundstücke und grundstücksgleiche Rechte", "asset", 0),
        new("0020", "Geschäftsbauten", "asset", 0),
        new("0027", "Wohnbauten", "asset", 0),
        new("0030", "Grundstückseinrichtungen", "asset", 0),
        new("0040", "Bauten auf fremden Grundstücken", "asset", 0),
        new("0050", "Technische Anlagen und Maschinen", "asset", 0),
        new("0060", "Herstellungskosten technische Anlagen", "asset", 0),
        new("0070", "Andere Anlagen, Betriebs- und Geschäftsausstattung", "asset", 0),
        new("0080", "Fuhrpark", "asset", 0),
        new("0085", "Geringwertige Wirtschaftsgüter (GWG)", "asset", 0),
        new("0090", "Geleistete Anzahlungen und Anlagen im Bau", "asset", 0),
        new("0100", "Finanzanlagen, Anteile an verbundenen Unternehmen", "asset", 0),
        new("0110", "Ausleihungen an verbundene Unternehmen", "asset", 0),
        new("0115", "Beteiligungen", "asset", 0),
        new("0135", "Wertpapiere des Anlagevermögens", "asset", 0),
        new("0200", "Aufwendungen für die Ingangsetzung", "asset", 0),
        new("0210", "Konzessionen, gewerbliche Schutzrechte", "asset", 0),
        new("0215", "Lizenzen", "asset", 0),
        new("0220", "Geschäfts- oder Firmenwert", "asset", 0),
        new("0260", "Geleistete Anzahlungen auf immaterielle VG", "asset", 0),
        new("0300", "Kumulierte Abschreibungen Sachanlagen", "asset", 0),
        new("0310", "Kumulierte Abschreibungen immaterielle VG", "asset", 0),
        new("0400", "Gezeichnetes Kapital / Stammkapital", "equity", 0),
        new("0420", "Kapitalrücklage", "equity", 0),
        new("0430", "Gewinnrücklagen, gesetzliche Rücklage", "equity", 0),
        new("0440", "Gewinnrücklagen, andere", "equity", 0),
        new("0450", "Gewinn-/Verlustvortrag", "equity", 0),
        new("0460", "Jahresüberschuss/-fehlbetrag", "equity", 0),
        new("0480", "Bilanzgewinn / Bilanzverlust", "equity", 0),
        new("0630", "Sonderposten Investitionszulagen", "equity", 0),
        new("0700", "Pensionsrückstellungen", "liability", 0),
        new("0710", "Steuerrückstellungen", "liability", 0),
        new("0720", "Sonstige Rückstellungen", "liability", 0),
        new("0730", "Rückstellungen für Gewährleistungen", "liability", 0),
        new("0740", "Rückstellungen für ausstehende Rechnungen", "liability", 0),
        new("0750", "Urlaubsrückstellungen", "liability", 0),
        new("0755", "Rückstellungen für Jahresabschlusskosten", "liability", 0),

        // Class 1: Finanz- und Privatkonten (Financial)
        new("1000", "Kasse", "asset", 1),
        new("1200", "Bank", "asset", 1),
        new("1210", "Bank 2", "asset", 1),
        new("1220", "Bank 3", "asset", 1),
        new("1300", "Wechsel", "asset", 1),
        new("1360", "Geldtransit", "asset", 1),
        new("1400", "Forderungen aus Lieferungen und Leistungen", "asset", 1),
        new("1410", "Forderungen aus L+L innergemeinschaftlich", "asset", 1),
        new("1420", "Forderungen aus L+L Drittland", "asset", 1),
        new("1450", "Forderungen gegen verbundene Unternehmen", "asset", 1),
        new("1460", "Forderungen gegen Unternehmen mit Beteiligungsverhältnis", "asset", 1),
        new("1500", "Sonstige Vermögensgegenstände", "asset", 1),
        new("1510", "Vorsteuer laufendes Jahr", "asset", 1),
        new("1511", "Vorsteuer 7%", "asset", 1),
        new("1518", "Bezahlte Einfuhrumsatzsteuer", "asset", 1),
        new("1540", "Steuerüberzahlungen", "asset", 1),
        new("1545", "Umsatzsteuerforderungen", "asset", 1),
        new("1548", "Vorsteuer im Folgejahr abziehbar", "asset", 1),
        new("1550", "Durchlaufende Posten", "asset", 1),
        new("1560", "Geleistete Anzahlungen (kurzfristig)", "asset", 1),
        new("1580", "Sonstige Forderungen gegen Personal", "asset", 1),
        new("1590", "Verrechnungskonto Gesellschafter", "asset", 1),
        new("1600", "Verbindlichkeiten aus Lieferungen und Leistungen", "liability", 1),
        new("1610", "Verbindlichkeiten aus L+L innergemeinschaftlich", "liability", 1),
        new("1620", "Verbindlichkeiten aus L+L Drittland", "liability", 1),
        new("1700", "Sonstige Verbindlichkeiten", "liability", 1),
        new("1710", "Erhaltene Anzahlungen (kurzfristig)", "liability", 1),
        new("1720", "Darlehen, kurzfristig", "liability", 1),
        new("1730", "Verbindlichkeiten gegenüber Kreditinstituten", "liability", 1),
        new("1740", "Verbindlichkeiten gegenüber verbundenen Unternehmen", "liability", 1),
        new("1750", "Verbindlichkeiten gegenüber Gesellschaftern", "liability", 1),
        new("1755", "Umsatzsteuer laufendes Jahr", "liability", 1),
        new("1756", "Umsatzsteuer 7%", "liability", 1),
        new("1760", "Umsatzsteuer Vorjahr", "liability", 1),
        new("1770", "Umsatzsteuer, nicht fällig", "liability", 1),
        new("1771", "USt-Vorauszahlung 1/11", "liability", 1),
        new("1774", "Lohnsteuerverbindlichkeiten", "liability", 1),
        new("1776", "Umsatzsteuer 19%", "liability", 1),
        new("1780", "Kapitalertragsteuer-Verbindlichkeiten", "liability", 1),
        new("1790", "Körperschaftsteuer-Verbindlichkeiten", "liability", 1),
        new("1791", "Gewerbesteuer-Verbindlichkeiten", "liability", 1),
        new("1792", "Solidaritätszuschlag-Verbindlichkeiten", "liability", 1),
        new("1800", "Privatentnahmen allgemein", "equity", 1),
        new("1890", "Privateinlagen", "equity", 1),

        // Class 2: Abgrenzungskonten (Accruals)
        new("2000", "Aktive Rechnungsabgrenzung", "asset", 2),
        new("2010", "Disagio", "asset", 2),
        new("2100", "Passive Rechnungsabgrenzung", "liability", 2),
        new("2200", "Körperschaftsteuer Aufwand", "expense", 2),
        new("2203", "Solidaritätszuschlag", "expense", 2),
        new("2204", "Gewerbesteuer Aufwand", "expense", 2),

        // Class 3: Wareneingang / Rohstoffe (Materials)
        new("3000", "Einsatzstoffe / Rohstoffe", "expense", 3),
        new("3100", "Fremdleistungen", "expense", 3),
        new("3200", "Wareneingang", "expense", 3),
        new("3300", "Wareneingang 7%", "expense", 3, "7"),
        new("3400", "Wareneingang 19%", "expense", 3, "19"),
        new("3420", "Innergemeinschaftlicher Erwerb 19%", "expense", 3, "19"),
        new("3425", "Innergemeinschaftlicher Erwerb 7%", "expense", 3, "7"),
        new("3550", "Steuerfreie Einfuhren", "expense", 3, "0"),
        new("3700", "Erhaltene Skonti", "revenue", 3),
        new("3730", "Erhaltene Boni", "revenue", 3),
        new("3736", "Erhaltene Rabatte", "revenue", 3),
        new("3800", "Bezugsnebenkosten", "expense", 3),
        new("3900", "Bestandsveränderungen Roh-, Hilfs-, Betriebsstoffe", "expense", 3),

        // Class 4: Betriebliche Aufwendungen (Operating Expenses)
        new("4000", "Materialaufwand", "expense", 4),
        new("4100", "Löhne", "expense", 4),
        new("4110", "Löhne Fertigung", "expense", 4),
        new("4120", "Gehälter", "expense", 4),
        new("4125", "Geschäftsführergehälter", "expense", 4),
        new("4130", "Gesetzliche soziale Aufwendungen", "expense", 4),
        new("4138", "Beiträge zur Berufsgenossenschaft", "expense", 4),
        new("4140", "Freiwillige soziale Aufwendungen", "expense", 4),
        new("4150", "Zuführung zu Pensionsrückstellungen", "expense", 4),
        new("4170", "Vermögenswirksame Leistungen", "expense", 4),
        new("4190", "Aushilfslöhne", "expense", 4),
        new("4200", "Raumkosten", "expense", 4),
        new("4210", "Miete (unbewegliche Wirtschaftsgüter)", "expense", 4),
        new("4215", "Nebenkosten", "expense", 4),
        new("4220", "Pacht", "expense", 4),
        new("4230", "Heizung", "expense", 4),
        new("4240", "Gas, Strom, Wasser", "expense", 4),
        new("4250", "Reinigung", "expense", 4),
        new("4260", "Instandhaltung betrieblicher Räume", "expense", 4),
        new("4300", "Versicherungen, Beiträge", "expense", 4),
        new("4360", "Versicherungen", "expense", 4),
        new("4380", "Beiträge", "expense", 4),
        new("4500", "Fahrzeugkosten", "expense", 4),
        new("4510", "Kfz-Steuern", "expense", 4),
        new("4520", "Kfz-Versicherungen", "expense", 4),
        new("4530", "Laufende Kfz-Betriebskosten", "expense", 4),
        new("4540", "Kfz-Reparaturen", "expense", 4),
        new("4550", "Kfz-Leasing", "expense", 4),
        new("4570", "Fremdfahrzeuge", "expense", 4),
        new("4580", "Sonstige Fahrzeugkosten", "expense", 4),
        new("4600", "Werbekosten", "expense", 4),
        new("4610", "Werbekosten", "expense", 4),
        new("4630", "Geschenke abziehbar", "expense", 4),
        new("4635", "Geschenke nicht abziehbar", "expense", 4),
        new("4640", "Repräsentationskosten", "expense", 4),
        new("4650", "Bewirtungskosten 70%", "expense", 4),
        new("4654", "Nicht abziehbare Bewirtung", "expense", 4),
        new("4660", "Reisekosten Arbeitnehmer", "expense", 4),
        new("4663", "Reisekosten Unternehmer Fahrtkosten", "expense", 4),
        new("4664", "Reisekosten Unternehmer Verpflegung", "expense", 4),
        new("4666", "Reisekosten Unternehmer Übernachtung", "expense", 4),
        new("4670", "Reisekosten Arbeitnehmer Fahrtkosten", "expense", 4),
        new("4674", "Reisekosten AN Verpflegung", "expense", 4),
        new("4676", "Reisekosten AN Übernachtung", "expense", 4),
        new("4700", "Kosten der Warenabgabe", "expense", 4),
        new("4710", "Verpackungsmaterial", "expense", 4),
        new("4730", "Ausgangsfrachten", "expense", 4),
        new("4750", "Aufwand für Gewährleistungen", "expense", 4),
        new("4800", "Reparaturen und Instandhaltung", "expense", 4),
        new("4806", "Wartungskosten EDV", "expense", 4),
        new("4810", "Mietleasing", "expense", 4),
        new("4820", "Abschreibungen Sachanlagen", "expense", 4),
        new("4822", "Abschreibungen immaterielle VG", "expense", 4),
        new("4824", "Abschreibungen GWG", "expense", 4),
        new("4830", "Abschreibungen auf Forderungen", "expense", 4),
        new("4840", "Außerplanmäßige Abschreibungen", "expense", 4),
        new("4900", "Sonstige betriebliche Aufwendungen", "expense", 4),
        new("4910", "Porto", "expense", 4),
        new("4920", "Telefon", "expense", 4),
        new("4921", "Internet, Online-Dienste", "expense", 4),
        new("4930", "Bürobedarf", "expense", 4),
        new("4940", "Zeitschriften, Bücher", "expense", 4),
        new("4945", "Fortbildungskosten", "expense", 4),
        new("4946", "Fremdarbeiten / Freelancer", "expense", 4),
        new("4950", "Rechts- und Beratungskosten", "expense", 4),
        new("4955", "Buchführungskosten", "expense", 4),
        new("4957", "Abschluss- und Prüfungskosten", "expense", 4),
        new("4960", "Nebenkosten des Geldverkehrs", "expense", 4),
        new("4965", "Mahngebühren", "expense", 4),
        new("4969", "Kreditgebühren", "expense", 4),
        new("4970", "Sonstige Aufwendungen", "expense", 4),
        new("4980", "Währungskursverluste", "expense", 4),

        // Class 7: Bestandsveränderungen (Inventory Changes)
        new("7000", "Bestandsveränderungen fertige Erzeugnisse", "revenue", 7),
        new("7050", "Bestandsveränderungen unfertige Erzeugnisse", "revenue", 7),
        new("7080", "Bestandsveränderungen unfertige Leistungen", "revenue", 7),
        new("7090", "Andere aktivierte Eigenleistungen", "revenue", 7),

        // Class 8: Erlöse (Revenue)
        new("8000", "Erlöse", "revenue", 8),
        new("8100", "Steuerfreie Umsätze § 4 Nr. 1a UStG (Export)", "revenue", 8, "0"),
        new("8110", "Steuerfreie innergemeinschaftliche Lieferungen", "revenue", 8, "0"),
        new("8120", "Steuerfreie Leistungen § 4 Nr. 1b UStG", "revenue", 8, "0"),
        new("8125", "Steuerfreie ig. Lieferungen § 4 Nr. 1b UStG", "revenue", 8, "0"),
        new("8200", "Erlöse 7%", "revenue", 8, "7"),
        new("8300", "Erlöse 19%", "revenue", 8, "19"),
        new("8400", "Erlöse 19% (allgemein)", "revenue", 8, "19"),
        new("8500", "Provisionserlöse", "revenue", 8, "19"),
        new("8520", "Erlöse aus Vermietung/Verpachtung", "revenue", 8, "19"),
        new("8540", "Erlöse aus Nebengeschäften", "revenue", 8, "19"),
        new("8600", "Sonstige Erlöse", "revenue", 8),
        new("8700", "Gewährte Skonti", "expense", 8),
        new("8710", "Gewährte Boni", "expense", 8),
        new("8720", "Gewährte Rabatte", "expense", 8),
        new("8730", "Erlösschmälerungen", "expense", 8),
        new("8800", "Erlöse aus Anlagenabgängen", "revenue", 8),
        new("8820", "Erträge aus Zuschreibungen", "revenue", 8),
        new("8900", "Sonstige betriebliche Erträge", "revenue", 8),
        new("8910", "Erträge aus Auflösung von Rückstellungen", "revenue", 8),
        new("8920", "Periodenfremde Erträge", "revenue", 8),
        new("8930", "Währungskursgewinne", "revenue", 8),
        new("8940", "Versicherungsentschädigungen", "revenue", 8),
        new("8950", "Erträge aus Mieteinnahmen", "revenue", 8),

        // Class 9: Vortrags- und statistische Konten (Statistical)
        new("9000", "Saldenvorträge Sachkonten", "equity", 9),
        new("9008", "Saldenvorträge Debitoren", "asset", 9),
        new("9009", "Saldenvorträge Kreditoren", "liability", 9),
    ];
}
